[project]
name="galspec"
version="0.0.1"
dependencies=[
    "numpy>=1.26.0",
    "matplotlib>=3.7.0",
    "h5py>=3.9.0",
    "tqdm>=4.66.1",
    "ete3>=3.1.3",
    "seaborn>=0.13.0",
    "Cython>=3.0.6",
    "colossus>=1.3.3",
    "bagpipes>=1.0.4",
    "treelib>=1.7.0",
    ]